"""
Regenerates data.js from ../heimdall_roadmap.xlsx.

Run this any time the spreadsheet changes (status updates, date shifts,
new rows, etc.) to refresh the web app:

    python build_data.py

Requires: pip install openpyxl
"""
import json
import datetime
import os

import openpyxl

SRC = os.path.join(os.path.dirname(__file__), "..", "heimdall_roadmap.xlsx")
OUT = os.path.join(os.path.dirname(__file__), "data.js")

FIELD_MAP = {
    "ID": "id",
    "Phase": "phase",
    "Task": "task",
    "Start Date": "start",
    "End Date": "end",
    "Duration (days)": "duration",
    "Status": "status",
    "Dependency": "dependency",
    "Milestone": "milestone",
    "Notes/Deliverable": "notes",
    "Automation Tier": "automationTier",
}


def main():
    wb = openpyxl.load_workbook(SRC, data_only=True)
    ws = wb[wb.sheetnames[0]]
    rows = list(ws.iter_rows(values_only=True))
    headers = rows[0]

    records = []
    for r in rows[1:]:
        if r[0] is None:
            continue
        raw = dict(zip(headers, r))
        rec = {}
        for src_key, dst_key in FIELD_MAP.items():
            v = raw.get(src_key)
            if isinstance(v, datetime.datetime):
                v = v.strftime("%Y-%m-%d")
            rec[dst_key] = v
        # merge any stray extra columns (wrapped notes text) into notes
        extra = raw.get(None)
        if extra:
            rec["notes"] = (rec.get("notes") or "").rstrip() + " " + str(extra).strip()
            rec["notes"] = rec["notes"].strip()
        rec["milestone"] = (rec.get("milestone") or "N").strip().upper() == "Y"
        rec["automationTier"] = (rec.get("automationTier") or "alert").strip().lower()
        rec["dependency"] = (
            [d.strip() for d in rec["dependency"].split(",")] if rec.get("dependency") else []
        )
        records.append(rec)

    # var (not const/let) so these attach to `window` for app.js to read.
    js = "// Auto-generated by build_data.py — do not edit by hand.\n"
    js += "var ROADMAP_DATA = " + json.dumps(records, indent=2) + ";\n"
    js += "var ROADMAP_GENERATED_AT = " + json.dumps(datetime.datetime.now().strftime("%Y-%m-%d %H:%M")) + ";\n"

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)

    print(f"Wrote {len(records)} tasks to {OUT}")


if __name__ == "__main__":
    main()
