// Auto-generated by build_data.py — do not edit by hand.
var ROADMAP_DATA = [
  {
    "id": "P0.1",
    "phase": "Phase 0 - Foundation (prior work)",
    "task": "Register UK Ltd Company",
    "start": null,
    "end": "2026-08-15",
    "duration": null,
    "status": "Done",
    "dependency": [],
    "milestone": false,
    "notes": "Confirm Companies House number on file"
  },
  {
    "id": "P0.2",
    "phase": "Phase 0 - Foundation (prior work)",
    "task": "Open business bank account",
    "start": null,
    "end": "2026-08-15",
    "duration": null,
    "status": "Done",
    "dependency": [],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P0.3",
    "phase": "Phase 0 - Foundation (prior work)",
    "task": "Purchase Professional Indemnity insurance",
    "start": null,
    "end": "2026-08-15",
    "duration": null,
    "status": "Done",
    "dependency": [],
    "milestone": false,
    "notes": "Verify Public Liability cover is also in place - doc only confirms PI"
  },
  {
    "id": "P0.4",
    "phase": "Phase 0 - Foundation (prior work)",
    "task": "Build Gold Master LZA config + baseline SCPs",
    "start": null,
    "end": "2026-08-15",
    "duration": null,
    "status": "Done",
    "dependency": [],
    "milestone": false,
    "notes": "Customer-agnostic controls / NFRs encoded as SCPs"
  },
  {
    "id": "P0.5",
    "phase": "Phase 0 - Foundation (prior work)",
    "task": "Complete NCSC Cloud Security Principles mapping",
    "start": null,
    "end": "2026-08-15",
    "duration": null,
    "status": "Done",
    "dependency": [],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P0.6",
    "phase": "Phase 0 - Foundation (prior work)",
    "task": "Cyber Essentials Basic self-assessment",
    "start": null,
    "end": "2026-08-15",
    "duration": null,
    "status": "Verify - status unclear",
    "dependency": [],
    "milestone": true,
    "notes": "RISK: this is a pass/fail gate for almost every public sector procurement route incl. G-Cloud. Confirm whether basic CE (not CE+) is actually done - resolve in P1.1 if not"
  },
  {
    "id": "P1.1",
    "phase": "Phase 1 - Compliance & Deliverables Packaging",
    "task": "Confirm/complete Cyber Essentials Basic (if not already done)",
    "start": "2026-08-17",
    "end": "2026-08-18",
    "duration": 2,
    "status": "Not Started",
    "dependency": [
      "P0.6"
    ],
    "milestone": true,
    "notes": "~GBP 300-600 self-assessment; blocking for procurement registration"
  },
  {
    "id": "P1.2",
    "phase": "Phase 1 - Compliance & Deliverables Packaging",
    "task": "Format NCSC Traceability Matrix into branded Excel/PDF",
    "start": "2026-08-18",
    "end": "2026-08-19",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P0.5"
    ],
    "milestone": false,
    "notes": "Columns: NCSC Principle / LZA-SCP Implementation / Security Hub Control ID / Audit Evidence Type"
  },
  {
    "id": "P1.3",
    "phase": "Phase 1 - Compliance & Deliverables Packaging",
    "task": "Write Executive Guardrails Summary (plain-English SCP breakdown)",
    "start": "2026-08-19",
    "end": "2026-08-20",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P0.4"
    ],
    "milestone": false,
    "notes": "1-2 pages non-technical stakeholder audience"
  },
  {
    "id": "P1.4",
    "phase": "Phase 1 - Compliance & Deliverables Packaging",
    "task": "Create Deployment Architecture Diagram",
    "start": "2026-08-20",
    "end": "2026-08-21",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P0.4"
    ],
    "milestone": false,
    "notes": "OU layout (Core/Security/Workloads/Sandbox) + log flow to Audit account conceptual only - no IP leakage"
  },
  {
    "id": "P1.5",
    "phase": "Phase 1 - Compliance & Deliverables Packaging",
    "task": "Draft DPIA template + SIRO briefing pack",
    "start": "2026-08-24",
    "end": "2026-08-25",
    "duration": 1,
    "status": "Not Started",
    "dependency": [],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P1.6",
    "phase": "Phase 1 - Compliance & Deliverables Packaging",
    "task": "Assemble Auditor Handover Pack (combine P1.2-P1.5)",
    "start": "2026-08-25",
    "end": "2026-08-26",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P1.2",
      "P1.3",
      "P1.4",
      "P1.5"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P1-M",
    "phase": "Phase 1 - Compliance & Deliverables Packaging",
    "task": "MILESTONE: Auditor-ready deliverable pack complete",
    "start": "2026-08-26",
    "end": "2026-08-26",
    "duration": 0,
    "status": "Not Started",
    "dependency": [
      "P1.6"
    ],
    "milestone": true,
    "notes": null
  },
  {
    "id": "P2.1",
    "phase": "Phase 2 - Commercial Collateral",
    "task": "Validate pricing vs comparable Contracts Finder awards",
    "start": "2026-08-26",
    "end": "2026-08-27",
    "duration": 1,
    "status": "Not Started",
    "dependency": [],
    "milestone": false,
    "notes": "Sanity-check the GBP 25k-40k assumption against 2-3 real awarded contract values"
  },
  {
    "id": "P2.2",
    "phase": "Phase 2 - Commercial Collateral",
    "task": "Draft 1-page Product Spec Datasheet (What not How)",
    "start": "2026-08-27",
    "end": "2026-08-28",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P2.1"
    ],
    "milestone": false,
    "notes": "Follow \"high feature low implementation\" rule"
  },
  {
    "id": "P2.3",
    "phase": "Phase 2 - Commercial Collateral",
    "task": "Add IP/confidentiality footer + review legal wording",
    "start": "2026-08-28",
    "end": "2026-08-28",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P2.2"
    ],
    "milestone": false,
    "notes": "Confidential & Proprietary footer on every page"
  },
  {
    "id": "P2.4",
    "phase": "Phase 2 - Commercial Collateral",
    "task": "Build 10-slide Executive Briefing Deck",
    "start": "2026-08-31",
    "end": "2026-09-02",
    "duration": 2,
    "status": "Not Started",
    "dependency": [
      "P2.2"
    ],
    "milestone": false,
    "notes": "For council Heads of IT / CISOs"
  },
  {
    "id": "P2.5",
    "phase": "Phase 2 - Commercial Collateral",
    "task": "Draft standard Statement of Work / engagement terms template",
    "start": "2026-09-02",
    "end": "2026-09-03",
    "duration": 1,
    "status": "Not Started",
    "dependency": [],
    "milestone": false,
    "notes": "Fixed scope / fixed price / 3-week delivery language"
  },
  {
    "id": "P2.6",
    "phase": "Phase 2 - Commercial Collateral",
    "task": "Design 1-page teaser summary for cold outreach",
    "start": "2026-09-03",
    "end": "2026-09-04",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P2.2"
    ],
    "milestone": false,
    "notes": "Lighter than full spec - used to earn the 15-min call before sharing full doc"
  },
  {
    "id": "P2-M",
    "phase": "Phase 2 - Commercial Collateral",
    "task": "MILESTONE: Sales collateral ready to send",
    "start": "2026-09-04",
    "end": "2026-09-04",
    "duration": 0,
    "status": "Not Started",
    "dependency": [
      "P2.2",
      "P2.4",
      "P2.5",
      "P2.6"
    ],
    "milestone": true,
    "notes": null
  },
  {
    "id": "P3.1",
    "phase": "Phase 3 - Procurement Infrastructure",
    "task": "Register AWS Marketplace Seller account + submit KYC",
    "start": "2026-09-07",
    "end": "2026-09-07",
    "duration": 1,
    "status": "Not Started",
    "dependency": [],
    "milestone": false,
    "notes": "1-3 week approval wait - kick off early do not block other phases on it"
  },
  {
    "id": "P3.2",
    "phase": "Phase 3 - Procurement Infrastructure",
    "task": "Submit Professional Services listing in AWS Partner Central",
    "start": "2026-09-08",
    "end": "2026-09-09",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P3.1"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P3.3",
    "phase": "Phase 3 - Procurement Infrastructure",
    "task": "Register as AWS Select Tier Partner (APN)",
    "start": "2026-09-09",
    "end": "2026-09-10",
    "duration": 1,
    "status": "Not Started",
    "dependency": [],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P3.4",
    "phase": "Phase 3 - Procurement Infrastructure",
    "task": "Create Contracts Finder supplier account + saved search alerts",
    "start": "2026-09-10",
    "end": "2026-09-10",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P1.1"
    ],
    "milestone": false,
    "notes": "Keywords: AWS, Landing Zone, Cloud Migration, Cloud Security"
  },
  {
    "id": "P3.5",
    "phase": "Phase 3 - Procurement Infrastructure",
    "task": "Register as supplier on Find a Tender Service",
    "start": "2026-09-10",
    "end": "2026-09-11",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P1.1"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P3.6",
    "phase": "Phase 3 - Procurement Infrastructure",
    "task": "Register on Supplier Registration Service (SSQ prep)",
    "start": "2026-09-11",
    "end": "2026-09-11",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P1.1"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P3.7",
    "phase": "Phase 3 - Procurement Infrastructure",
    "task": "Research next G-Cloud application window and diarise it",
    "start": "2026-09-11",
    "end": "2026-09-11",
    "duration": 1,
    "status": "Not Started",
    "dependency": [],
    "milestone": false,
    "notes": "Frameworks reopen every 12-18 months - do not miss the window"
  },
  {
    "id": "P3-M",
    "phase": "Phase 3 - Procurement Infrastructure",
    "task": "MILESTONE: Procurement channels live",
    "start": "2026-09-25",
    "end": "2026-09-25",
    "duration": 0,
    "status": "Not Started",
    "dependency": [
      "P3.1",
      "P3.4",
      "P3.5",
      "P3.6"
    ],
    "milestone": true,
    "notes": "Marketplace approval typically lands around this date"
  },
  {
    "id": "P4.1",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "Mine Contracts Finder for expiring AWS/cloud contracts (awarded 2-3yr ago)",
    "start": "2026-09-14",
    "end": "2026-09-15",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P3.4"
    ],
    "milestone": false,
    "notes": "Log every hit in heimdall_outreach_tracker.csv"
  },
  {
    "id": "P4.2",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "Shortlist top 10 councils/NHS trusts/housing associations by fit + expiry date",
    "start": "2026-09-15",
    "end": "2026-09-16",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P4.1"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P4.3",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "Identify LinkedIn contacts (Head of Digital / CIO / CISO) for shortlist",
    "start": "2026-09-16",
    "end": "2026-09-18",
    "duration": 2,
    "status": "Not Started",
    "dependency": [
      "P4.2"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P4.4",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "Set up outreach tracker workflow",
    "start": "2026-09-18",
    "end": "2026-09-18",
    "duration": 1,
    "status": "Not Started",
    "dependency": [],
    "milestone": false,
    "notes": "See heimdall_outreach_tracker.csv"
  },
  {
    "id": "P4.5",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "Send outreach batch 1 (5 contacts)",
    "start": "2026-09-21",
    "end": "2026-09-21",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P2.6",
      "P4.3"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P4.6",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "Send outreach batch 2 (5 contacts)",
    "start": "2026-09-28",
    "end": "2026-09-28",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P2.6",
      "P4.3"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P4.7",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "Follow up batch 1 (7-day follow-up)",
    "start": "2026-09-28",
    "end": "2026-09-28",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P4.5"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P4.8",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "Follow up batch 2 (7-day follow-up)",
    "start": "2026-10-05",
    "end": "2026-10-05",
    "duration": 1,
    "status": "Not Started",
    "dependency": [
      "P4.6"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P4.9",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "Outreach to 3 regional AWS MSPs re: subcontracting",
    "start": "2026-09-21",
    "end": "2026-09-25",
    "duration": 3,
    "status": "Not Started",
    "dependency": [
      "P3.3"
    ],
    "milestone": false,
    "notes": "Alternate channel - MSPs winning council work who lack AWS security depth"
  },
  {
    "id": "P4-M",
    "phase": "Phase 4 - Lead Generation (Mining & Outreach)",
    "task": "MILESTONE: First 10 warm conversations initiated",
    "start": "2026-10-05",
    "end": "2026-10-05",
    "duration": 0,
    "status": "Not Started",
    "dependency": [
      "P4.7",
      "P4.8"
    ],
    "milestone": true,
    "notes": null
  },
  {
    "id": "P5.1",
    "phase": "Phase 5 - Conversations & Pilot/PoC",
    "task": "Book and run 15-min peer exchange calls as replies land",
    "start": "2026-10-12",
    "end": "2026-11-13",
    "duration": 32,
    "status": "Not Started",
    "dependency": [
      "P4-M"
    ],
    "milestone": false,
    "notes": "Ongoing - log outcomes in tracker"
  },
  {
    "id": "P5.2",
    "phase": "Phase 5 - Conversations & Pilot/PoC",
    "task": "Qualify interested prospects (budget/timeline/authority)",
    "start": "2026-10-19",
    "end": "2026-11-20",
    "duration": 32,
    "status": "Not Started",
    "dependency": [
      "P5.1"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P5.3",
    "phase": "Phase 5 - Conversations & Pilot/PoC",
    "task": "Propose scoped pilot/PoC to 1-2 warm prospects",
    "start": "2026-11-02",
    "end": "2026-11-06",
    "duration": 4,
    "status": "Not Started",
    "dependency": [
      "P5.2"
    ],
    "milestone": false,
    "notes": "e.g. mini healthcheck or paid discovery workshop"
  },
  {
    "id": "P5.4",
    "phase": "Phase 5 - Conversations & Pilot/PoC",
    "task": "Deliver pilot/PoC engagement",
    "start": "2026-11-09",
    "end": "2026-11-27",
    "duration": 18,
    "status": "Not Started",
    "dependency": [
      "P5.3"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P5.5",
    "phase": "Phase 5 - Conversations & Pilot/PoC",
    "task": "Capture case study / testimonial from pilot",
    "start": "2026-11-30",
    "end": "2026-12-04",
    "duration": 4,
    "status": "Not Started",
    "dependency": [
      "P5.4"
    ],
    "milestone": false,
    "notes": "First proof point for future outreach"
  },
  {
    "id": "P5.6",
    "phase": "Phase 5 - Conversations & Pilot/PoC",
    "task": "Contingency: second outreach wave (next 10 contacts) if batch 1-2 stall",
    "start": "2026-10-26",
    "end": "2026-10-30",
    "duration": 4,
    "status": "Not Started",
    "dependency": [
      "P4-M"
    ],
    "milestone": false,
    "notes": "Trigger only if response rate from P4 is low"
  },
  {
    "id": "P5-M",
    "phase": "Phase 5 - Conversations & Pilot/PoC",
    "task": "MILESTONE (core goal): Pilot/PoC delivered with a council or NHS trust",
    "start": "2026-11-27",
    "end": "2026-11-27",
    "duration": 0,
    "status": "Not Started",
    "dependency": [
      "P5.4"
    ],
    "milestone": true,
    "notes": null
  },
  {
    "id": "P6.1",
    "phase": "Phase 6 - Conversion to Paid Contract",
    "task": "Convert pilot relationship into fixed-price proposal",
    "start": "2026-12-07",
    "end": "2026-12-11",
    "duration": 4,
    "status": "Not Started",
    "dependency": [
      "P5-M"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P6.2",
    "phase": "Phase 6 - Conversion to Paid Contract",
    "task": "Complete SSQ / procurement paperwork for target authority",
    "start": "2026-12-14",
    "end": "2027-01-08",
    "duration": 25,
    "status": "Not Started",
    "dependency": [
      "P6.1"
    ],
    "milestone": false,
    "notes": "Spans Christmas/New Year - expect council-side slowdown build in buffer"
  },
  {
    "id": "P6.3",
    "phase": "Phase 6 - Conversion to Paid Contract",
    "task": "Negotiate and finalise SOW / contract terms",
    "start": "2027-01-11",
    "end": "2027-01-29",
    "duration": 18,
    "status": "Not Started",
    "dependency": [
      "P6.2"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P6.4",
    "phase": "Phase 6 - Conversion to Paid Contract",
    "task": "Sign first paid contract",
    "start": "2027-02-01",
    "end": "2027-02-05",
    "duration": 4,
    "status": "Not Started",
    "dependency": [
      "P6.3"
    ],
    "milestone": true,
    "notes": null
  },
  {
    "id": "P6.5",
    "phase": "Phase 6 - Conversion to Paid Contract",
    "task": "Kick off delivery",
    "start": "2027-02-08",
    "end": "2027-02-15",
    "duration": 7,
    "status": "Not Started",
    "dependency": [
      "P6.4"
    ],
    "milestone": false,
    "notes": null
  },
  {
    "id": "P6-M",
    "phase": "Phase 6 - Conversion to Paid Contract",
    "task": "MILESTONE (stretch goal): First paid contract signed",
    "start": "2027-02-05",
    "end": "2027-02-05",
    "duration": 0,
    "status": "Not Started",
    "dependency": [
      "P6.4"
    ],
    "milestone": true,
    "notes": "6-month stretch target"
  },
  {
    "id": "X.1",
    "phase": "Ongoing/Parallel",
    "task": "Cyber Essentials Plus (CE+)",
    "start": "2026-11-02",
    "end": "2026-11-13",
    "duration": 10,
    "status": "Not Started",
    "dependency": [],
    "milestone": false,
    "notes": "Deliberately deferred until pipeline momentum exists (per prior decision) - revisit once a live deal is in Phase 5"
  },
  {
    "id": "X.2",
    "phase": "Ongoing/Parallel",
    "task": "G-Cloud framework application (if window opens)",
    "start": null,
    "end": null,
    "duration": null,
    "status": "Not Started",
    "dependency": [
      "P3.7"
    ],
    "milestone": true,
    "notes": "Date TBD - depends on P3.7 research; update this row once the next window is known"
  }
];
var ROADMAP_GENERATED_AT = "2026-08-15 08:48";
